In [1]:
import os
import re
import unicodedata
import numpy as np
import pandas as pd
from getpass import getuser


# =============================
# CONFIG
# =============================
USER = getuser()
INPUT_DIR = f"C:/Users/{USER}/Documents/GitHub/tennis-homophily/data/atp/"

MEN_MATCHES_FILE  = os.path.join(INPUT_DIR, "men_matches.xlsx")
MEN_RANKINGS_FILE = os.path.join(INPUT_DIR, "men_rankings.xlsx")
OUTPUT_FILE       = os.path.join(INPUT_DIR, "men_matches_with_ranks.xlsx")

TOURN_COL      = "tournament"
TOURN_CODE_COL = "tournament_code"
STAGE_COL      = "stage"
RANK_COL       = "rank_num"

PLAYER_ROLES = [
    ("winners_p1_surname", "winners_p1"),
    ("winners_p2_surname", "winners_p2"),
    ("losers_p1_surname",  "losers_p1"),
    ("losers_p2_surname",  "losers_p2"),
]


# =============================
# Helpers
# =============================
def normalize_tournament(s):
    if pd.isna(s):
        return None
    return " ".join(str(s).lower().strip().split())


def remove_accents(s):
    if pd.isna(s):
        return None
    text = unicodedata.normalize("NFKD", str(s))
    return "".join(ch for ch in text if not unicodedata.combining(ch))


SURNAME_ALIASES = {
    "zhizhen": "zhang",
    "puetz": "putz",
    "đere": "djere",       # Laslo Đere: Đ (D-with-stroke) does not NFKD-decompose
    "vinolas": "ramos-vinolas", # Albert Ramos-Viñolas: Wikipedia uses just Viñolas
    "?ere": "djere",
    "vinolas": "ramos-vinolas",
}

# Non-ASCII initial characters that do not NFKD-decompose to their ASCII base
INITIAL_ALIASES = {
    "ł": "l",   # Łukasz Kubot: Polish ł stays ł after NFKD; scraper stores "ł" or "łukasz"
}

def normalize_surname(s):
    if pd.isna(s):
        return None
    name = " ".join(remove_accents(s).lower().strip().split())
    return SURNAME_ALIASES.get(name, name)


def extract_initial(s):
    """
    Extract first alphabetic character as initial from a name string.
    Works with 'Mike Bryan(6)', 'R. Ram', etc.
    Handles non-ASCII initials: checks INITIAL_ALIASES before falling back
    to the first ASCII letter (avoids 'łukasz' → 'u' instead of 'l').
    """
    if pd.isna(s):
        return None
    s = str(s).strip()
    if not s:
        return None
    # Check first character for known non-ASCII aliases (e.g. ł → l)
    first_ch = s[0].lower()
    if first_ch in INITIAL_ALIASES:
        return INITIAL_ALIASES[first_ch]
    m = re.search(r"[A-Za-z]", s)
    return m.group(0).lower() if m else None


def get_unique_rankings(rk_df, keys):
    """
    From rankings df, keep only rows for which the key combination `keys`
    appears exactly once.
    """
    counts = (
        rk_df
        .groupby(keys, dropna=False)[RANK_COL]
        .size()
        .reset_index(name="n")
    )
    uniq_keys = counts[counts["n"] == 1][keys]
    return rk_df.merge(uniq_keys, on=keys, how="inner")


def collapse_special_rank(rk_df, special_rules, rank_col=RANK_COL):
    """
    For players listed in `special_rules` (dict: (surname, initial) -> set(years_min)),
    if there are multiple rows with the same (tourn_key, surname, initial, year),
    keep only one:

      - if year ∈ years_min  -> keep row with lowest rank_num  (= correct/better player)
      - else                 -> keep row with highest rank_num (= correct/worse player)
    """
    if not special_rules:
        return rk_df

    rk = rk_df.copy()

    mask_special = False
    for (s, i) in special_rules.keys():
        mask_special |= (rk["surname"] == s) & (rk["initial"] == i)

    special = rk[mask_special].copy()
    rest    = rk[~mask_special].copy()

    if special.empty:
        return rk_df

    grp_keys = ["tourn_key", "surname", "initial", "year"]
    keep_idx = []

    special[rank_col] = pd.to_numeric(special[rank_col], errors="coerce")

    for (tk, s, i, yr), g in special.groupby(grp_keys):
        years_min = special_rules.get((s, i), set())

        if g[rank_col].notna().any():
            if yr in years_min:
                idx = g[rank_col].idxmin()
            else:
                idx = g[rank_col].idxmax()
        else:
            idx = g.index[0]

        keep_idx.append(idx)

    special_single = special.loc[keep_idx].copy()
    out = pd.concat([rest, special_single], ignore_index=True)

    return out


def assign_twins_min_rank_per_match(
    merged_long,
    rankings,
    twins,
    profile_cols,
    rank_col=RANK_COL,
    roles=("losers_p1", "losers_p2"),
):
    """
    For each (surname, initial) in `twins`, if in a given match (tourn_key, year, match_id)
    there are multiple unmatched rows for that player in the specified `roles`,
    and there are at least as many ranking rows for that (tourn_key, year),
    assign distinct ranking/profile rows to them.

    - Within a (tourn_key, year) we sort rankings by rank_num ascending (best first)
      and assign sequentially
    - Only fills rows where rank_num is currently NaN
    """
    ml = merged_long.copy()

    for surname, initial in twins:
        s = surname.lower()
        i = initial.lower()

        rk_twin = rankings[
            (rankings["surname"] == s) &
            (rankings["initial"] == i) &
            rankings[rank_col].notna()
        ].copy()

        if rk_twin.empty:
            continue

        mask_unmatched = (
            (ml["surname"] == s) &
            (ml["initial"] == i) &
            ml[rank_col].isna() &
            ml["role"].isin(roles)
        )

        if not mask_unmatched.any():
            continue

        twin_unmatched = ml[mask_unmatched]

        for (tk, yr, mid), grp in twin_unmatched.groupby(
            ["tourn_key", "year", "match_id"]
        ):
            cand = rk_twin[
                (rk_twin["tourn_key"] == tk) &
                (rk_twin["year"] == yr)
            ].sort_values(rank_col)

            if cand.empty:
                continue

            k = min(len(grp), len(cand))
            cand_use = cand.head(k)

            for (idx_row, _), (_, rk_row) in zip(grp.iloc[:k].iterrows(),
                                                cand_use.iterrows()):
                for col in [rank_col] + profile_cols:
                    if col in rk_row.index:
                        ml.at[idx_row, col] = rk_row[col]

    return ml


def build_unmatched_report(merged_long, rankings, key_cols, rank_col=RANK_COL):
    """
    Return a dataframe with one row per unmatched player (match_id, role)
    and diagnostics about why the rank_num was not attached.
    """
    unmatched = merged_long[
        merged_long[rank_col].isna()
    ][["match_id", "role", "tourn_key", "year", "surname", "initial", "rank_hint"]].copy()

    if unmatched.empty:
        print("All players matched a ranking row.")
        return unmatched

    for col in ["tourn_key", "surname", "initial"]:
        if col == "surname":
            unmatched[col] = unmatched[col].map(normalize_surname).astype("string")
            rankings[col]  = rankings[col].map(normalize_surname).astype("string")
        else:
            unmatched[col] = unmatched[col].astype("string").str.lower().str.strip()
            rankings[col]  = rankings[col].astype("string").str.lower().str.strip()

    unmatched["year"] = pd.to_numeric(unmatched["year"], errors="coerce").astype("Int64")
    rankings["year"]  = pd.to_numeric(rankings["year"], errors="coerce").astype("Int64")

    cand_counts = (
        rankings
        .groupby(key_cols, dropna=False)[rank_col]
        .size()
        .reset_index(name="n_candidates")
    )

    diag = unmatched.merge(cand_counts, on=key_cols, how="left")
    diag["n_candidates"] = diag["n_candidates"].fillna(0).astype(int)

    def classify_reason(row):
        if row["n_candidates"] == 0:
            return "no ranking row for this (tourn_key, surname, initial, year)"
        if row["n_candidates"] > 1 and pd.isna(row["rank_hint"]):
            return "multiple ranking candidates and no rank_hint"
        if row["n_candidates"] > 1 and pd.notna(row["rank_hint"]):
            return "multiple ranking candidates but rank_hint matched none"
        return "generic inconsistency"

    diag["reason"] = diag.apply(classify_reason, axis=1)
    return diag.sort_values(["reason", "surname", "initial", "year", "tourn_key"])


def inspect_player_keys(players_long, rankings, surname="surname", initial="i"):
    s = surname.lower()
    i = initial.lower()

    pl = players_long[
        (players_long["surname"] == s) &
        (players_long["initial"] == i)
    ].copy()

    print("=== In players_long (matches) ===")
    if pl.empty:
        print("No rows for", s, i)
    else:
        display(
            pl[["match_id", "role", "tourn_key", "year", "rank_hint"]]
            .sort_values(["year", "tourn_key", "role"])
        )

    rk = rankings[
        (rankings["surname"] == s) &
        (rankings["initial"] == i)
    ].copy()

    print("\n=== In rankings ===")
    if rk.empty:
        print("No rows for", s, i, "in rankings.")
    else:
        display(
            rk[["tourn_key", "year", RANK_COL]]
            .sort_values(["year", "tourn_key", RANK_COL])
        )

    match_pairs = set(map(tuple, pl[["tourn_key", "year"]].drop_duplicates().to_numpy())) if not pl.empty else set()
    rank_pairs  = set(map(tuple, rk[["tourn_key", "year"]].drop_duplicates().to_numpy())) if not rk.empty else set()

    print("\n(tourn_key, year) in MATCHES:", match_pairs)
    print("(tourn_key, year) in RANKINGS:", rank_pairs)
    print("In MATCHES but not RANKINGS:", match_pairs - rank_pairs)


# =============================
# Load data
# =============================
matches  = pd.read_excel(MEN_MATCHES_FILE)
rankings = pd.read_excel(MEN_RANKINGS_FILE)


# =============================
# tourn_key in both tables
# =============================
if "tourn_key" not in matches.columns:
    if TOURN_COL not in matches.columns:
        raise KeyError(f"'tourn_key' or '{TOURN_COL}' must be in matches.")
    matches["tourn_key"] = matches[TOURN_COL].map(normalize_tournament)

if "tourn_key" not in rankings.columns:
    if TOURN_COL not in rankings.columns:
        raise KeyError(f"'tourn_key' or '{TOURN_COL}' must be in rankings.")
    rankings["tourn_key"] = rankings[TOURN_COL].map(normalize_tournament)


# =============================
# Ensure 'year' exists
# =============================
if "year" not in matches.columns:
    raise KeyError("matches needs a 'year' column.")

if "year" not in rankings.columns:
    if "dateweek" in rankings.columns:
        rankings["year"] = pd.to_datetime(rankings["dateweek"], errors="coerce").dt.year
    else:
        raise KeyError("rankings needs a 'year' column or 'dateweek' to derive it.")


# =============================
# Ensure 'date' and 'dateweek' exist
# =============================
if "date" not in matches.columns:
    matches["date"] = pd.to_datetime(matches["year"].astype(str) + "-07-01", errors="coerce")
else:
    matches["date"] = pd.to_datetime(matches["date"], errors="coerce")

if "dateweek" not in rankings.columns:
    rankings["dateweek"] = pd.to_datetime(rankings["year"].astype(str) + "-07-01", errors="coerce")
else:
    rankings["dateweek"] = pd.to_datetime(rankings["dateweek"], errors="coerce")


# =============================
# Create unique match_id
# =============================
matches = matches.reset_index(drop=True).copy()
matches["match_id"] = matches.index


# =============================
# Create initials in matches if missing
# =============================
for surname_col, role in PLAYER_ROLES:
    base = surname_col.replace("_surname", "")
    initial_col = f"{base}_initial"

    if initial_col in matches.columns:
        continue

    name_col = f"{base}_name"
    if name_col in matches.columns:
        matches[initial_col] = matches[name_col].apply(extract_initial)
        continue

    if base in matches.columns:
        matches[initial_col] = matches[base].apply(extract_initial)
        continue

    raise KeyError(
        f"Cannot create {initial_col}: neither '{name_col}' nor '{base}' found in matches."
    )


# =============================
# Prepare rankings: surname, initial, rank_num, dtypes
# =============================
if "player_surname" not in rankings.columns or "player_initial" not in rankings.columns:
    raise KeyError("rankings must contain 'player_surname' and 'player_initial' columns.")

rankings["surname"] = rankings["player_surname"].map(normalize_surname)
rankings["initial"] = rankings["player_initial"].astype(str).str.lower().str.strip().str[0]

for col in ["tourn_key", "surname", "initial"]:
    if col == "surname":
        rankings[col] = rankings[col].map(normalize_surname)
    else:
        rankings[col] = rankings[col].astype(str).str.lower().str.strip()

rankings["year"] = pd.to_numeric(rankings["year"], errors="coerce").astype("Int64")

rankings[RANK_COL] = (
    rankings[RANK_COL].astype(str).str.strip()
    .str.replace(r"[^0-9]+$", "", regex=True)
)
rankings[RANK_COL] = pd.to_numeric(rankings[RANK_COL], errors="coerce").astype("Int64")


# =============================
# Special rank rules
# =============================
# Each entry: (surname, initial) -> set of years where the LOWER rank_num is correct.
# Used when two different players share the same (surname, initial) in the rankings file.
#
# murray, j  (2018):   Jamie Murray (rank ~9-13) vs unknown J. Murray (rank ~1300)
#                      Jamie is the target player; years_min={2018} -> keep lower rank.
# gonzalez, m (2022-23): Maximo Gonzalez (rank ~20-50) vs unknown M. Gonzalez (rank ~1600+)
#                        Maximo is the target; years_min={2022,2023} -> keep lower rank.
# lopez, m:  Feliciano Lopez (lower rank, better player) vs Marc Lopez
#            years_min={2018..2021} -> keep lower rank (Feliciano in those years).
SPECIAL_RANK_RULES = {
    ("lopez",    "m"): {2018, 2019, 2020, 2021},
    ("chung",    "h"): {2018},
    ("zhang",    "z"): {2019, 2023},
    ("martin",   "a"): {2021},
    ("smith",    "j"): {2022, 2023},
    ("martinez", "l"): {2023},
    ("nakashima","b"): {2023},
    # --- added 2026-05-18: newly discovered ambiguous players ---
    ("murray",   "j"): {2018},              # Jamie Murray (rank 9-13) vs other J. Murray (~1300)
    ("gonzalez", "m"): {2022, 2023},        # Maximo Gonzalez (rank 20-50) vs other M. Gonzalez (~1600+)
}

rankings = collapse_special_rank(rankings, SPECIAL_RANK_RULES, rank_col=RANK_COL)

# Players whose first-name initial differs across scrape sources
# (same player, not two different players — use SPECIAL_RANK_RULES for the latter)
INITIAL_OVERRIDES = {
    ("balaji", "s"): "n",   # N. Sriram Balaji: 2018-early23 → "n.sriram" (n); 2023+ → "s"/"sriram" (s)
}


# =============================
# Split ranking columns by level
# =============================
PLAYER_KEYS = ["surname", "initial"]
YEAR_KEYS   = ["surname", "initial", "year"]
EVENT_KEYS  = ["tourn_key", "surname", "initial", "year"]

FIXED_COLS = [
    "dob",
    "turned-pro",
    "country",
    "coach",
    "singles_career_high_rank",
    "singles_date_career_high_rank",
    "singles_titles_career",
    "singles_wins_career",
    "singles_losses_career",
    "singles_win_ratio_career",
    "weight-lbs",
    "weight-kg",
    "height-ft",
    "height-in",
    "height-cm",
    "birthplace-city",
    "birthplace-country",
    "hand",
    "backhand",
    "colonial_legacy",
    "federal_legacy",
    "country_std",
    "iso3",
    "dob_dt",
    "singles_rank_date_dt",
    "singles_career_high_rank_num",
]

YEAR_COLS = [
    "experience_double",
]

EVENT_COLS = [
    "dateweek",
    "dateweek_dt",
    "doubles_titles-ytd",
    "doubles_titles-career",
    "doubles_wins-ytd",
    "doubles_losses-ytd",
    "doubles_wins-career",
    "doubles_losses-career",
    "doubles_win_ratio-ytd",
    "doubles_win_ratio-career",
    "days_since_single_career_high_rank",
    "age_at_single_career_high_rank_years",
    "age_at_career_high_rank_days",
    "top100_within_1y",
    "top100_within_5y",
    "top100_within_10y",
    "gap_1y",
    "gap_5y",
    "gap_10y",
    "abs_gap_1y",
    "abs_gap_5y",
    "abs_gap_10y",
    "single_specialist",
]

FIXED_COLS = [c for c in FIXED_COLS if c in rankings.columns]
YEAR_COLS  = [c for c in YEAR_COLS if c in rankings.columns]
EVENT_COLS = [c for c in EVENT_COLS if c in rankings.columns]

profile_cols = FIXED_COLS + YEAR_COLS + EVENT_COLS

player_fixed_df = (
    rankings[PLAYER_KEYS + FIXED_COLS]
    .drop_duplicates(subset=PLAYER_KEYS)
    .copy()
)

player_year_df = (
    rankings[YEAR_KEYS + YEAR_COLS]
    .drop_duplicates(subset=YEAR_KEYS)
    .copy()
)

player_event_df = (
    rankings[EVENT_KEYS + EVENT_COLS]
    .drop_duplicates(subset=EVENT_KEYS)
    .copy()
)


# =============================
# Build players_long with surname, initial, rank_hint
# =============================
long_rows = []

for surname_col, role in PLAYER_ROLES:
    if surname_col not in matches.columns:
        raise KeyError(f"Missing column: {surname_col}")

    base = surname_col.replace("_surname", "")
    initial_col = f"{base}_initial"
    match_ranking_col = f"{base}_ranking"

    if initial_col not in matches.columns:
        raise KeyError(f"Missing column: {initial_col}")
    if match_ranking_col not in matches.columns:
        raise KeyError(f"Missing column: {match_ranking_col}")

    tmp = matches[[
        "match_id",
        "tourn_key",
        "year",
        "date",
        surname_col,
        initial_col,
        match_ranking_col
    ]].copy()

    tmp.rename(columns={
        surname_col: "surname",
        initial_col: "initial",
        match_ranking_col: "rank_hint"
    }, inplace=True)

    tmp["surname"] = tmp["surname"].astype(str).str.lower().str.strip()
    tmp["initial"] = tmp["initial"].astype(str).str.lower().str.strip().str[0]

    tmp["rank_hint"] = (
        tmp["rank_hint"].astype(str).str.strip()
        .str.replace(r"[^0-9]+$", "", regex=True)
    )
    tmp["rank_hint"] = pd.to_numeric(tmp["rank_hint"], errors="coerce").astype("Int64")

    tmp["role"] = role
    long_rows.append(tmp)

players_long = pd.concat(long_rows, ignore_index=True)
players_long = players_long.sort_values(["match_id", "role"], ignore_index=True)

for col in ["tourn_key", "surname", "initial"]:
    if col == "surname":
        players_long[col] = players_long[col].map(normalize_surname)
    else:
        players_long[col] = players_long[col].astype(str).str.lower().str.strip()
players_long["year"]      = pd.to_numeric(players_long["year"], errors="coerce").astype("Int64")
players_long["rank_hint"] = pd.to_numeric(players_long["rank_hint"], errors="coerce").astype("Int64")

# Apply per-(surname, initial) overrides for same-player initial inconsistencies
for (sn, old_ini), new_ini in INITIAL_OVERRIDES.items():
    mask = (players_long["surname"] == sn) & (players_long["initial"] == old_ini)
    if mask.any():
        players_long.loc[mask, "initial"] = new_ini
        print(f"  INITIAL_OVERRIDES: {sn!r} {old_ini!r} → {new_ini!r} ({mask.sum()} rows fixed)")


# =============================
# Merge fixed + year + event layers
# =============================
merged_long = players_long.copy()

if FIXED_COLS:
    merged_long = merged_long.merge(
        player_fixed_df,
        on=["surname", "initial"],
        how="left"
    )

if YEAR_COLS:
    merged_long = merged_long.merge(
        player_year_df,
        on=["surname", "initial", "year"],
        how="left"
    )

if EVENT_COLS:
    merged_long = merged_long.merge(
        player_event_df,
        on=["tourn_key", "surname", "initial", "year"],
        how="left"
    )


# =============================
# Hierarchical rank_num merge
# 1) surname-only within event/year
# 2) surname+initial within event/year
# 3) surname+initial+rank_hint
# =============================
for col in ["tourn_key", "surname", "initial"]:
    if col == "surname":
        rankings[col] = rankings[col].map(normalize_surname)
    else:
        rankings[col] = rankings[col].astype(str).str.lower().str.strip()
rankings["year"]   = pd.to_numeric(rankings["year"], errors="coerce").astype("Int64")
rankings[RANK_COL] = pd.to_numeric(rankings[RANK_COL], errors="coerce").astype("Int64")

unmatched     = merged_long.copy()
matched_parts = []

key1 = ["tourn_key", "surname", "year"]
key2 = ["tourn_key", "surname", "initial", "year"]

rk1 = get_unique_rankings(rankings.dropna(subset=[RANK_COL]), key1)

m1 = unmatched.merge(
    rk1[key1 + [RANK_COL]],
    on=key1,
    how="left",
    indicator=True,
    suffixes=("", "_rk")
)

matched1 = m1[m1["_merge"] == "both"].drop(columns="_merge")
unmatched = m1[m1["_merge"] == "left_only"][merged_long.columns]
matched_parts.append(matched1)

rk2 = get_unique_rankings(rankings.dropna(subset=[RANK_COL]), key2)

m2 = unmatched.merge(
    rk2[key2 + [RANK_COL]],
    on=key2,
    how="left",
    indicator=True,
    suffixes=("", "_rk")
)

matched2 = m2[m2["_merge"] == "both"].drop(columns="_merge")
unmatched = m2[m2["_merge"] == "left_only"][merged_long.columns]
matched_parts.append(matched2)

u3 = unmatched[unmatched["rank_hint"].notna()].copy()
rk3 = rankings[rankings[RANK_COL].notna()].copy()

m3 = u3.merge(
    rk3[key2 + [RANK_COL]],
    left_on=key2 + ["rank_hint"],
    right_on=key2 + [RANK_COL],
    how="left",
    indicator=True,
    suffixes=("", "_rk")
)

matched3 = m3[m3["_merge"] == "both"].drop(columns="_merge")
matched_parts.append(matched3)

# =============================
# Fallback 1: n_candidates == 1, pick lowest rank
# =============================
u4 = unmatched[unmatched["rank_hint"].isna()].copy()
if not u4.empty:
    cand1_counts = (
        rankings[rankings[RANK_COL].notna()]
        .groupby(key2, dropna=False)[RANK_COL]
        .size()
        .reset_index(name="n_cand")
    )
    cand1_best = (
        rankings[rankings[RANK_COL].notna()]
        .sort_values(RANK_COL)
        .drop_duplicates(subset=key2, keep="first")
        .merge(
            cand1_counts[cand1_counts["n_cand"] == 1],
            on=key2,
            how="inner"
        )[key2 + [RANK_COL]]
    )

    m4 = u4.merge(
        cand1_best,
        on=key2,
        how="left",
        indicator=True,
        suffixes=("", "_rk")
    )

    matched4 = m4[m4["_merge"] == "both"].drop(columns="_merge")
    if not matched4.empty:
        matched_parts.append(matched4)
        unmatched = m4[m4["_merge"] == "left_only"][merged_long.columns]

# =============================
# Fallback 2: closest date for same (surname, initial, year)
# =============================
u5 = unmatched[unmatched["rank_hint"].isna()].copy()
if not u5.empty:
    fill_merge = u5[['match_id', 'role', 'surname', 'initial', 'year', 'date']].merge(
        rankings[['surname', 'initial', 'year', 'dateweek', RANK_COL]],
        on=['surname', 'initial', 'year'],
        how='left',
        suffixes=('_match', '_rank')
    )

    fill_merge = fill_merge[fill_merge[RANK_COL].notna()].copy()

    if not fill_merge.empty:
        fill_merge['date_rank']  = pd.to_datetime(fill_merge['dateweek'], errors='coerce')
        fill_merge['date_match'] = pd.to_datetime(fill_merge['date'],     errors='coerce')
        fill_merge['date_diff']  = (fill_merge['date_match'] - fill_merge['date_rank']).dt.days.abs()
        fill_merge = fill_merge.sort_values(['match_id', 'role', 'date_diff', RANK_COL])
        fill_merge = fill_merge.drop_duplicates(subset=['match_id', 'role'], keep='first')

        matched5 = u5.merge(
            fill_merge[['match_id', 'role', RANK_COL]],
            on=['match_id', 'role'],
            how='inner'
        )

        if not matched5.empty:
            matched_parts.append(matched5)
            unmatched = u5[~u5.set_index(['match_id', 'role']).index.isin(
                matched5.set_index(['match_id', 'role']).index)].copy()

matched3_idx = matched3.set_index(["match_id", "role"]).index
unmatched_final = unmatched[
    ~unmatched.set_index(["match_id", "role"]).index.isin(matched3_idx)
].copy()

if RANK_COL not in unmatched_final.columns:
    unmatched_final[RANK_COL] = pd.NA

merged_ranked = pd.concat(matched_parts + [unmatched_final], ignore_index=True)


# =============================
# Special handling for twins
# =============================
TWINS = {("ratiwatana", "s")}

merged_long = assign_twins_min_rank_per_match(
    merged_long=merged_ranked,
    rankings=rankings,
    twins=TWINS,
    profile_cols=profile_cols,
    rank_col=RANK_COL,
    roles=("losers_p1", "losers_p2"),
)


# =============================
# Build wide profiles per role
# =============================
role_frames = []

for surname_col, role in PLAYER_ROLES:
    cols_to_keep = [RANK_COL] + profile_cols

    role_df = (
        merged_long[merged_long["role"] == role]
        .drop_duplicates(subset=["match_id"])
        .set_index("match_id")[cols_to_keep]
        .add_prefix(f"{role}_")
    )
    role_frames.append(role_df)

profiles_wide = pd.concat(role_frames, axis=1)


# =============================
# Join back to matches
# =============================
result = (
    matches
    .set_index("match_id")
    .join(profiles_wide, how="left")
    .reset_index()
)


# =============================
# Save output
# =============================
result.to_excel(OUTPUT_FILE, index=False)
print(f"Saved merged file with rankings:\n{OUTPUT_FILE}")


# =============================
# Diagnostics
# =============================
key_cols = ["tourn_key", "surname", "initial", "year"]

unmatched_report = build_unmatched_report(
    merged_long=merged_long,
    rankings=rankings,
    key_cols=key_cols,
    rank_col=RANK_COL
)

  INITIAL_OVERRIDES: 'balaji' 's' → 'n' (17 rows fixed)

Saved merged file with rankings:
C:/Users/ALESSANDRO/Documents/GitHub/tennis-homophily/data/atp/men_matches_with_ranks.xlsx

In [2]:
# ============================================================
# CELL 1b: Fallback-6 — cross-year closest-date matching
# ============================================================
# All previous fallbacks constrain on year.  Fallback-6 drops that constraint
# so players who exist in the rankings file but have no entry for the specific
# (tourn_key, year) of their match can be matched to the nearest available
# ranking date across all years.
#
# Fixes:
#   - djere    : 2019/2022/2023 matches but only 2021/2024 ranking entries
#   - o'connell: AO2025 match, rankings from earlier years (apostrophe in name
#                is consistent in both files; no SURNAME_ALIASES entry needed)
#   - Olympics players (monfils, alcaraz, busta, monteiro, nishikori, raonic):
#                no "olympics" tourn_key in rankings, use nearest GS ranking

n_unmatched_before = merged_long[RANK_COL].isna().sum()
print(f"Unmatched before Fallback-6: {n_unmatched_before}")

still_unmatched = merged_long[merged_long[RANK_COL].isna()].copy()

if not still_unmatched.empty:
    fill6 = still_unmatched[['match_id', 'role', 'surname', 'initial', 'date']].merge(
        rankings[['surname', 'initial', 'dateweek', RANK_COL]],
        on=['surname', 'initial'],
        how='left'
    )
    fill6 = fill6[fill6[RANK_COL].notna()].copy()

    if not fill6.empty:
        fill6['_dm'] = pd.to_datetime(fill6['date'], errors='coerce')
        fill6['_dr'] = pd.to_datetime(fill6['dateweek'], errors='coerce')
        fill6['_dd'] = (fill6['_dm'] - fill6['_dr']).dt.days.abs()
        fill6 = (
            fill6
            .sort_values(['match_id', 'role', '_dd', RANK_COL])
            .drop_duplicates(subset=['match_id', 'role'], keep='first')
        )

        fill6_dict = fill6.set_index(['match_id', 'role'])[RANK_COL].to_dict()

        for (mid, role), rank_val in fill6_dict.items():
            mask = (merged_long['match_id'] == mid) & (merged_long['role'] == role)
            merged_long.loc[mask, RANK_COL] = rank_val

        print(f"Fallback-6 matched {len(fill6_dict)} players via cross-year nearest ranking")
    else:
        print("Fallback-6: no candidates found (these players are absent from rankings file)")

n_unmatched_after = merged_long[RANK_COL].isna().sum()
print(f"Unmatched after  Fallback-6: {n_unmatched_after}")

if n_unmatched_after > 0:
    still = merged_long[merged_long[RANK_COL].isna()][
        ['match_id', 'role', 'tourn_key', 'year', 'surname', 'initial']
    ].drop_duplicates(['surname', 'initial'])
    print("\nPlayers still absent from rankings file entirely:")
    print(still.to_string(index=False))

# Re-run wide-profile build and save (overwrites the Cell 0 save with improved ranks)
role_frames_f6 = []
for surname_col, role in PLAYER_ROLES:
    cols_to_keep = [RANK_COL] + profile_cols
    role_df = (
        merged_long[merged_long["role"] == role]
        .drop_duplicates(subset=["match_id"])
        .set_index("match_id")[cols_to_keep]
        .add_prefix(f"{role}_")
    )
    role_frames_f6.append(role_df)

profiles_wide_f6 = pd.concat(role_frames_f6, axis=1)
result_f6 = (
    matches
    .set_index("match_id")
    .join(profiles_wide_f6, how="left")
    .reset_index()
)
result_f6.to_excel(OUTPUT_FILE, index=False)
print(f"\nSaved updated rankings file: {OUTPUT_FILE}")

Unmatched before Fallback-6: 71
Fallback-6 matched 57 players via cross-year nearest ranking
Unmatched after  Fallback-6: 14

Players still absent from rankings file entirely:
 match_id       role       tourn_key  year   surname initial
        6 winners_p2 australian open  2018     lopez       g
      913  losers_p2       wimbledon  2021       NaN     NaN
     1277  losers_p1   roland garros  2023   gasquet       r
     1361 winners_p2         us open  2023    husler       m
     1482  losers_p2 australian open  2024 prashanth       v
     1896 winners_p1         us open  2025    exsted       m

Saved updated rankings file: C:/Users/ALESSANDRO/Documents/GitHub/tennis-homophily/data/atp/men_matches_with_ranks.xlsx

In [3]:
display(unmatched_report)
print("Total unmatched players:", len(unmatched_report))

,match_id,role,tourn_key,year,surname,initial,rank_hint,n_candidates,reason
46,1532,winners_p1,olympics,2024,alcaraz,c,<NA>,0,"no ranking row for this (tourn_key, surname, i..."
50,1544,winners_p1,olympics,2024,alcaraz,c,<NA>,0,"no ranking row for this (tourn_key, surname, i..."
53,1551,losers_p1,olympics,2024,alcaraz,c,<NA>,0,"no ranking row for this (tourn_key, surname, i..."
13,538,losers_p1,australian open,2020,andujar,p,<NA>,0,"no ranking row for this (tourn_key, surname, i..."
4,337,losers_p1,roland garros,2019,bourgue,m,<NA>,0,"no ranking row for this (tourn_key, surname, i..."
...,...,...,...,...,...,...,...,...,...
28,1300,losers_p2,roland garros,2023,varillas,j,<NA>,0,"no ranking row for this (tourn_key, surname, i..."
30,1351,losers_p2,us open,2023,varillas,j,<NA>,0,"no ranking row for this (tourn_key, surname, i..."
40,1424,losers_p2,wimbledon,2023,varillas,j,<NA>,0,"no ranking row for this (tourn_key, surname, i..."
21,904,losers_p2,wimbledon,2021,ward,j,<NA>,0,"no ranking row for this (tourn_key, surname, i..."
23,913,losers_p2,wimbledon,2021,<NA>,<NA>,<NA>,0,"no ranking row for this (tourn_key, surname, i..."

Total unmatched players: 71

In [4]:
# Save unique unmatched report entries and inspect possible Zhizhen Zhang match
unique_unmatched = (
    unmatched_report
    .drop_duplicates(subset=["surname", "initial", "tourn_key", "year", "rank_hint", "reason"])
    .sort_values(["surname", "initial", "year", "tourn_key"])
)

unique_unmatched_file = os.path.join(INPUT_DIR, "unmatched_report_unique.csv")
unique_unmatched.to_csv(unique_unmatched_file, index=False)
print(f"Saved {len(unique_unmatched)} unique unmatched rows to {unique_unmatched_file}")

unique_surnames = sorted(unique_unmatched["surname"].dropna().astype(str).unique())
unique_surnames_file = os.path.join(INPUT_DIR, "unmatched_report_unique_surnames.txt")
with open(unique_surnames_file, "w", encoding="utf-8") as f:
    f.write("\n".join(unique_surnames))
print(f"Saved {len(unique_surnames)} unique unmatched surnames to {unique_surnames_file}")

# Check whether 'zhizhen' appears in the unmatched report
zhizhen_rows = unmatched_report[unmatched_report["surname"] == "zhizhen"].copy()
if not zhizhen_rows.empty:
    display(zhizhen_rows)
    print("Found unmatched report rows with surname 'zhizhen'. This may correspond to Zhizhen Zhang.")
else:
    print("No rows with surname 'zhizhen' were found in the unmatched report.")

Saved 56 unique unmatched rows to C:/Users/ALESSANDRO/Documents/GitHub/tennis-homophily/data/atp/unmatched_report_unique.csv
Saved 36 unique unmatched surnames to C:/Users/ALESSANDRO/Documents/GitHub/tennis-homophily/data/atp/unmatched_report_unique_surnames.txt
No rows with surname 'zhizhen' were found in the unmatched report.

In [5]:
# Example inspection
inspect_player_keys(players_long, rankings, "monfils", "g")

=== In players_long (matches) ===

      match_id        role tourn_key  year  rank_hint
3021       755   losers_p2  olympics  2021       <NA>
2971       742  winners_p2  olympics  2021       <NA>
6188      1547   losers_p1  olympics  2024       <NA>
6154      1538  winners_p1  olympics  2024       <NA>

=== In rankings ===

             tourn_key  year  rank_num
307    australian open  2018       315
1895     roland garros  2018       237
5496           us open  2018       516
3567         wimbledon  2018       242
6906   australian open  2019       271
7857     roland garros  2019       340
9693           us open  2019       438
8722         wimbledon  2019       342
33604          us open  2022       530
35597  australian open  2023       539
37582    roland garros  2023       540
39584        wimbledon  2023       558

(tourn_key, year) in MATCHES: {('olympics', 2021), ('olympics', 2024)}
(tourn_key, year) in RANKINGS: {('australian open', 2019), ('us open', 2019), ('roland garros', 2018), ('wimbledon', 2019), ('us open', 2022), ('us open', 2018), ('australian open', 2018), ('wimbledon', 2018), ('roland garros', 2023), ('wimbledon', 2023), ('australian open', 2023), ('roland garros', 2019)}
In MATCHES but not RANKINGS: {('olympics', 2021), ('olympics', 2024)}

In [6]:
# ============================================================
# CELL 5: Unmatched-player audit and fill strategies
# ============================================================
# All 49 unique unmatched players have reason = 'no ranking row for (tourn_key, surname, initial, year)'.
# Categorised into two groups:
#   A. Olympics-only: played Olympics but no entry in GS-based rankings file.
#      Fill strategy: use their ranking at the nearest GS in the same year.
#      For retired players (monfils, nishikori, raonic): use last available GS ranking.
#   B. GS players absent from rankings: no entry at all, or spelling mismatch.
#      Fill strategy: check SURNAME_ALIASES, or scrape ATP profile.

OLYMPICS_PLAYERS = [
    ('alcaraz',   'c'),   # Carlos Alcaraz 2024
    ('busta',     'p'),   # Pablo Carreno Busta 2024
    ('monfils',   'g'),   # Gael Monfils 2021, 2024 (use last available GS ranking)
    ('monteiro',  't'),   # Thiago Monteiro 2024
    ('nishikori', 'k'),   # Kei Nishikori 2024 (retired; last available)
    ('raonic',    'm'),   # Milos Raonic 2024 (retired; last available)
]

GS_MISSING = [
    # (surname, initial, note)
    ('andujar',    'p', 'Pablo Andujar - AO2020'),
    ('bourgue',    'm', 'Mathias Bourgue - RG2019'),
    ('brooksby',   'j', 'Jenson Brooksby - 2025'),
    ('cazaux',     'a', 'Arthur Cazaux - RG2020'),
    ('coria',      'f', 'Federico Coria - AO2023'),
    ('damm',       'm', 'Martin Damm - USO2019'),
    ('djere',      'l', 'Laslo Djere - 2019-2025 (4 tournaments)'),
    ('escobedo',   'e', 'Ernesto Escobedo - USO2020'),
    ('frusina',    'a', 'Alexander Frusina - USO2023'),
    ('galan',      'd', 'Daniel E. Galan - USO/Wim 2023'),
    ('ganesan',    'a', 'Adhithya Ganesan - USO2023'),
    ('gasquet',    'r', 'Richard Gasquet - RG2023'),
    ('gojo',       'b', 'Borna Gojo - AO2025'),
    ('gombos',     'n', 'Norbert Gombos - Wim2021'),
    ('gorzny',     's', 'Sem Gorzny - USO2022 (spelling?)'),
    ('jubb',       'p', 'Paul Jubb - Wim2019'),
    ('knowle',     'j', 'Julian Knowle - 2021 (veteran, retired)'),
    ('kodat',      't', 'Toby Kodat - USO2019'),
    ('lu',         'y', 'Yen-Hsun Lu - AO2020'),
    ('mchugh',     'a', 'Alex McHugh - Wim2018'),
    ('medjedovic', 'h', 'Hamad Medjedovic - USO2025'),
    ('moutet',     'c', 'Corentin Moutet - Wim2023'),
    ('oconnell',   'c', "Christopher O'Connell - AO2025 (apostrophe in surname)"),
    ('prashanth',  'v', 'Vishnu Vardhan Prashanth - AO2024/2025'),
    ('smith',      'c', 'C.Smith - USO2025 (possible name collision)'),
    ('varillas',   'j', 'Juan Pablo Varillas - 2023 all 4 GS'),
    ('ward',       'j', 'James Ward - Wim2021'),
]

print('=== A. Olympics-only players ===')
print('Strategy: find their GS doubles ranking for the same year as the Olympics entry.')
print()
for sur, ini in OLYMPICS_PLAYERS:
    cands = rankings[
        (rankings['surname'] == sur) & (rankings['initial'] == ini)
    ][['tourn_key','year',RANK_COL]].sort_values(['year',RANK_COL])
    if cands.empty:
        print(f'  {sur},{ini}: ABSENT from rankings -> scrape ATP profile')
    else:
        print(f'  {sur},{ini}: available rankings below')
        print(cands.to_string(index=False))
    print()

print()
print('=== B. GS-missing players - any fallback available? ===')
print('Strategy: add SURNAME_ALIASES entry, or scrape ATP profile.')
print()
for sur, ini, note in GS_MISSING:
    cands = rankings[
        (rankings['surname'] == sur) & (rankings['initial'] == ini)
    ]
    if cands.empty:
        status = 'ABSENT -> scrape ATP'
    else:
        yrs = sorted(cands['year'].dropna().unique())
        status = f'HAS entries for years {yrs} -> use closest-date fallback or verify tourn_key'
    print(f'  {sur},{ini}: {note}')
    print(f'    {status}')
    print()

print('=== Action summary ===')
print('  1. Olympics players (alcaraz,busta,monteiro,nishikori,raonic,monfils):')
print('     -> Add "olympics" as a valid tourn_key in rankings, OR')
print('        impute from nearest GS ranking of the same year.')
print('  2. Players absent from rankings entirely:')
print('     -> Scrape their ATP player profile and add to men_rankings.xlsx.')
print("  3. oconnell: apostrophe in surname prevents matching.")
print("     -> Add SURNAME_ALIASES entry: {\"o'connell\": \"oconnell\"} or normalise the apostrophe.")
print('  4. gorzny: possible spelling variant.')
print('     -> Cross-check ATP ID; correct spelling is Sem Verbeek (Dutch player) or check.')

=== A. Olympics-only players ===
Strategy: find their GS doubles ranking for the same year as the Olympics entry.

  alcaraz,c: available rankings below
      tourn_key  year  rank_num
  roland garros  2022       528
      wimbledon  2022       535
        us open  2022       537
australian open  2023       548

  busta,p: available rankings below
      tourn_key  year  rank_num
australian open  2018        42
      wimbledon  2018        65
  roland garros  2018        71
        us open  2018        78
australian open  2019        84
        us open  2019       119
  roland garros  2019       147
      wimbledon  2019       150
        us open  2020        46
  roland garros  2020        50
australian open  2020        80
australian open  2021        54
  roland garros  2021        65
      wimbledon  2021        69
       olympics  2021        77
        us open  2021       181
      wimbledon  2022       285
australian open  2022       286
        us open  2022       313
  roland garros  2022       332
australian open  2023       331
  roland garros  2023       550
      wimbledon  2023       854
australian open  2025       861
  roland garros  2025       870
      wimbledon  2025       885
        us open  2025       888

  monfils,g: available rankings below
      tourn_key  year  rank_num
  roland garros  2018       237
      wimbledon  2018       242
australian open  2018       315
        us open  2018       516
australian open  2019       271
  roland garros  2019       340
      wimbledon  2019       342
        us open  2019       438
        us open  2022       530
australian open  2023       539
  roland garros  2023       540
      wimbledon  2023       558

  monteiro,t: available rankings below
      tourn_key  year  rank_num
  roland garros  2018       507
      wimbledon  2018       573
        us open  2018       596
australian open  2018       629
      wimbledon  2019       297
  roland garros  2019       303
australian open  2019       336
        us open  2019       360
        us open  2020       214
  roland garros  2020       217
australian open  2020       538
        us open  2021       176
       olympics  2021       180
      wimbledon  2021       188
  roland garros  2021       194
australian open  2021       234
australian open  2022       161
      wimbledon  2022       222
  roland garros  2022       233
        us open  2022       265
australian open  2023       404
australian open  2025       567
  roland garros  2025       572
        us open  2025       575
      wimbledon  2025       587

  nishikori,k: available rankings below
      tourn_key  year  rank_num
  roland garros  2019       346
      wimbledon  2019       347
        us open  2019       445
australian open  2020       448
        us open  2020       459
  roland garros  2020       465
australian open  2021       510
  roland garros  2021       803
      wimbledon  2021       818
       olympics  2021       824
        us open  2021       824
australian open  2022       791

  raonic,m: available rankings below
      tourn_key  year  rank_num
      wimbledon  2019       346
        us open  2019       444
  roland garros  2019       450
australian open  2019       455
  roland garros  2020       356
australian open  2020       711
        us open  2020       733
australian open  2021       387
  roland garros  2021       536
      wimbledon  2021       641
        us open  2021       653
       olympics  2021       655
australian open  2022       629
  roland garros  2022      1037


=== B. GS-missing players - any fallback available? ===
Strategy: add SURNAME_ALIASES entry, or scrape ATP profile.

  andujar,p: Pablo Andujar - AO2020
    HAS entries for years [np.int64(2018), np.int64(2019), np.int64(2021), np.int64(2022), np.int64(2023)] -> use closest-date fallback or verify tourn_key

  bourgue,m: Mathias Bourgue - RG2019
    HAS entries for years [np.int64(2020), np.int64(2021), np.int64(2022)] -> use closest-date fallback or verify tourn_key

  brooksby,j: Jenson Brooksby - 2025
    HAS entries for years [np.int64(2018), np.int64(2019), np.int64(2020)] -> use closest-date fallback or verify tourn_key

  cazaux,a: Arthur Cazaux - RG2020
    HAS entries for years [np.int64(2021), np.int64(2022), np.int64(2025)] -> use closest-date fallback or verify tourn_key

  coria,f: Federico Coria - AO2023
    HAS entries for years [np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2024), np.int64(2025)] -> use closest-date fallback or verify tourn_key

  damm,m: Martin Damm - USO2019
    HAS entries for years [np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)] -> use closest-date fallback or verify tourn_key

  djere,l: Laslo Djere - 2019-2025 (4 tournaments)
    HAS entries for years [np.int64(2021), np.int64(2022), np.int64(2024)] -> use closest-date fallback or verify tourn_key

  escobedo,e: Ernesto Escobedo - USO2020
    HAS entries for years [np.int64(2018), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)] -> use closest-date fallback or verify tourn_key

  frusina,a: Alexander Frusina - USO2023
    HAS entries for years [np.int64(2025)] -> use closest-date fallback or verify tourn_key

  galan,d: Daniel E. Galan - USO/Wim 2023
    HAS entries for years [np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2025)] -> use closest-date fallback or verify tourn_key

  ganesan,a: Adhithya Ganesan - USO2023
    HAS entries for years [np.int64(2024), np.int64(2025)] -> use closest-date fallback or verify tourn_key

  gasquet,r: Richard Gasquet - RG2023
    ABSENT -> scrape ATP

  gojo,b: Borna Gojo - AO2025
    HAS entries for years [np.int64(2018), np.int64(2020), np.int64(2021), np.int64(2022)] -> use closest-date fallback or verify tourn_key

  gombos,n: Norbert Gombos - Wim2021
    HAS entries for years [np.int64(2018), np.int64(2019)] -> use closest-date fallback or verify tourn_key

  gorzny,s: Sem Gorzny - USO2022 (spelling?)
    HAS entries for years [np.int64(2024), np.int64(2025)] -> use closest-date fallback or verify tourn_key

  jubb,p: Paul Jubb - Wim2019
    HAS entries for years [np.int64(2018)] -> use closest-date fallback or verify tourn_key

  knowle,j: Julian Knowle - 2021 (veteran, retired)
    HAS entries for years [np.int64(2018)] -> use closest-date fallback or verify tourn_key

  kodat,t: Toby Kodat - USO2019
    HAS entries for years [np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)] -> use closest-date fallback or verify tourn_key

  lu,y: Yen-Hsun Lu - AO2020
    HAS entries for years [np.int64(2018), np.int64(2021), np.int64(2022)] -> use closest-date fallback or verify tourn_key

  mchugh,a: Alex McHugh - Wim2018
    HAS entries for years [np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)] -> use closest-date fallback or verify tourn_key

  medjedovic,h: Hamad Medjedovic - USO2025
    HAS entries for years [np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)] -> use closest-date fallback or verify tourn_key

  moutet,c: Corentin Moutet - Wim2023
    HAS entries for years [np.int64(2018), np.int64(2019)] -> use closest-date fallback or verify tourn_key

  oconnell,c: Christopher O'Connell - AO2025 (apostrophe in surname)
    ABSENT -> scrape ATP

  prashanth,v: Vishnu Vardhan Prashanth - AO2024/2025
    ABSENT -> scrape ATP

  smith,c: C.Smith - USO2025 (possible name collision)
    HAS entries for years [np.int64(2018)] -> use closest-date fallback or verify tourn_key

  varillas,j: Juan Pablo Varillas - 2023 all 4 GS
    HAS entries for years [np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2024), np.int64(2025)] -> use closest-date fallback or verify tourn_key

  ward,j: James Ward - Wim2021
    HAS entries for years [np.int64(2018), np.int64(2019)] -> use closest-date fallback or verify tourn_key

=== Action summary ===
  1. Olympics players (alcaraz,busta,monteiro,nishikori,raonic,monfils):
     -> Add "olympics" as a valid tourn_key in rankings, OR
        impute from nearest GS ranking of the same year.
  2. Players absent from rankings entirely:
     -> Scrape their ATP player profile and add to men_rankings.xlsx.
  3. oconnell: apostrophe in surname prevents matching.
     -> Add SURNAME_ALIASES entry: {"o'connell": "oconnell"} or normalise the apostrophe.
  4. gorzny: possible spelling variant.
     -> Cross-check ATP ID; correct spelling is Sem Verbeek (Dutch player) or check.